"""Rebuild losslessly subsetted fonts and WebP delivery copies; keep originals.

Run from any directory with Python + fonttools[woff], brotli, Pillow installed.
No network access is needed. Generated CSS retains every original Unicode
mapping and variable axis, so later content additions still have font coverage.
"""
from pathlib import Path
from fontTools import subset
from fontTools.ttLib import TTFont
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "fonts/noto"


def ranges(chars):
    result = []
    start = end = None
    for code in sorted(chars):
        if end is not None and code == end + 1:
            end = code
            continue
        if start is not None:
            result.append(f"U+{start:X}" + (f"-{end:X}" if end != start else ""))
        start = end = code
    if start is not None:
        result.append(f"U+{start:X}" + (f"-{end:X}" if end != start else ""))
    return ",".join(result)


def build_fonts():
    output = FONT_DIR / "subsets"
    output.mkdir(exist_ok=True)
    homepage = {ord(c) for c in (ROOT / "index.html").read_text()}
    site = {ord(c) for p in [*ROOT.glob("*.html"), *ROOT.glob("*.js")]
            for c in p.read_text()}
    css = ["/* Generated by scripts/optimize-assets.py; full Unicode coverage, on demand. */"]
    for filename, family, style in [
        ("NotoSans-Variable", "Noto Sans", "normal"),
        ("NotoSans-Italic-Variable", "Noto Sans", "italic"),
        ("NotoSansSC-Variable", "Noto Sans SC", "normal"),
    ]:
        source = FONT_DIR / f"{filename}.woff2"
        font = TTFont(source)
        remaining = set(font.getBestCmap())
        original_chars = remaining.copy()
        axes = [(a.axisTag, a.minValue, a.defaultValue, a.maxValue) for a in font["fvar"].axes]
        font.close()
        groups = []
        # The language button must not fetch a full Chinese page font in English.
        common = [("latin", set(range(0x250)) | set(range(0x2000, 0x2070))) ]
        if family == "Noto Sans SC":
            common += [("switch", {ord(c) for c in "中文"}), ("home", homepage)]
        common += [("site", site)]
        for name, wanted in common:
            selected = remaining & wanted
            if selected:
                groups.append((name, selected))
                remaining -= selected
        # Disjoint fallback blocks retain characters not currently used on site.
        ordered = sorted(remaining)
        for i in range(0, len(ordered), 512):
            groups.append((f"extra-{i // 512:02}", set(ordered[i:i + 512])))
        covered = set()
        for name, chars in groups:
            target = output / f"{filename}-{name}.woff2"
            font = TTFont(source)
            options = subset.Options()
            options.layout_features = ["*"]
            worker = subset.Subsetter(options=options)
            worker.populate(unicodes=chars)
            worker.subset(font)
            font.save(target)
            font.close()
            check = TTFont(target)
            assert set(check.getBestCmap()) == chars, target
            assert [(a.axisTag, a.minValue, a.defaultValue, a.maxValue) for a in check["fvar"].axes] == axes
            check.close()
            assert not covered & chars
            covered |= chars
            stretch = "font-stretch:62.5% 100%;" if family == "Noto Sans" else ""
            css.append(f'@font-face{{font-family:"{family}";font-style:{style};font-weight:100 900;'
                       f'{stretch}font-display:swap;src:url("fonts/noto/subsets/{target.name}") '
                       f'format("woff2");unicode-range:{ranges(chars)}}}')
            print(f"{target.name}: {target.stat().st_size:,} bytes", flush=True)
        assert covered == original_chars
    # Keep fonts in the existing stylesheet to avoid another render-blocking request.
    style = ROOT / "style.css"
    body = style.read_text()
    body = body[body.index(":root{"):]
    style.write_text("\n".join(css) + "\n" + body)


def build_images():
    names = ["three-electrode-deco-cubist", "cover-art-acs-electrochemistry-cubist",
             "cover-art-chemistry-materials-cubist", "cover-art-jpcc-cubist", "cover-art-jacs-au-cubist"]
    for name in names:
        with Image.open(ROOT / "assets" / f"{name}.png") as original:
            for width in (800, 1536):
                img = original.resize((width, round(original.height * width / original.width)), Image.Resampling.LANCZOS)
                target = ROOT / "assets" / f"{name}-{width}.webp"
                img.save(target, "WEBP", quality=82, method=6)
                print(f"{target.name}: {target.stat().st_size:,} bytes", flush=True)
    for name in ("gtiit", "technion1"):
        with Image.open(ROOT / "img" / f"{name}.png") as img:
            # Preserve every pixel and the transparency of the institution marks.
            img.save(ROOT / "img" / f"{name}.webp", "WEBP", lossless=True, method=6)


if __name__ == "__main__":
    build_images()
    build_fonts()
